# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: cifar100
  max_steps: 5000
  val_check_interval: 500
model:
  model_name: vit-b16-224-in21k
  training_mode: lora
  optimizer: sgd
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
  lora_r: 8
  lora_alpha: 8
data:
  dataset: cifar100
  root: data/
  size: 224
  batch_size: 128
  workers: 4
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
